### ISSUE TITLE
[Client] QA반영 + 부수사항

### ISSUE THREAD

**Issue by SuRyeon-Lee** [codestates-seb/seb40_main_016#166]
## 💁 설명

> Github 이슈 설명
각종 미뤄왔던 수정 및 보충 사항들을 작업합니다.

## 📑 체크리스트
> 구현해야 하는 이슈 체크리스트

- [x] 글 삭제시 바로 삭제되는 상태 ➡️ 삭제 컨펌 모달 띄우기
- [x] 회원가입 오타 수정
- [x] 회원가입 안되는 이슈해결
- [x] 간식 수량 제한
- [ ] 상태코드에 따른 에러 핸들링 -> 일단 다되어 있는거 같아서 발견되면 또 추가할 예정
- [x] 상세페이지 이미지 로딩인디케이터 추가
- [x] 날짜 제 시간에 뜨도록 하기 => 정민님이 설정해 주시기로 함
- [x] 404페이지 제작 및 연결
- [ ] 좋아요 중복 오류 해결

## ⏰ 예상 작업 시간
> 1d

**Comment by ssunip** [comment]
오 qa 수정하셨군요! 흑흑 소셜로그인 구현에 부수사항 반영까지 수고하셨습니당 😆
