### ISSUE TITLE
[Client] 팔로워 목록이 UI를 벗남

### ISSUE THREAD

**Issue by jaybknd** [codestates-seb/seb40_main_016#185]
## 🚒 버그 설명
팔로워 목록이 4명 이상인 경우 이후 유저가 흰 배경을 벗어납니다.

## ✔️ 기대하는 결과
팔로워 목록 전체에 흰색 배경이 적용되어야 합니다

## 🗒 참고자료
<img src="https://user-images.githubusercontent.com/107941815/205594954-1030f923-908f-41ed-9986-2981fc2e86cc.jpg" width="400">

**Comment by ssunip** [comment]
수정했습니다~ 아직 배포를 안해서 배포 링크로는 적용이 안되었습니다!

**Comment by jaybknd** [comment]
네. 알겠습니다. 배포 이후 확인하고 닫을께요~

**Comment by jaybknd** [comment]
수정 완료 확인했습니다.
